-- create Database DatabaseName
-- create database mytestDB

-- switch to the database just created 
use mytestDB

--Start Transactions 
begin transaction createtables 

--create a table

create table PERSON
			(
			PERSONID INT UNIQUE NOT NULL,
			LAST_NAME VARCHAR(255) NOT NULL,
			FIRST_NAME VARCHAR(255) NOT NULL,
			ADDRESS VARCHAR(255),
			CITY VARCHAR(50),
			EMAIL NVARCHAR(100) NOT NULL UNIQUE,
			CONSTRAINT PK_ON_PERSON_TABLE PRIMARY KEY(PERSONID)
			)

-- INSERT VALUES INTO THE NEW TABLE 
INSERT INTO PERSON
			VALUES(
				1, 'JOHN', 'BOLU', '27 AWOLOWO WAY', 'IKEJA', 'JBOLU@GMAIL.COM'
				)

SELECT * FROM PERSON

--DELETING YOUR DATABASE 
-- DROP DATABASE NAME_OF_DATABASE

-- BACKUP DATABASE 
/*
BACKUP DATABASE mytestDB
to disk = 'filepath'
*/

-- sql alter table statement 
-- this can be used to add, delete or modify 
-- columns in an existng table 

ALTER TABLE PERSON
ADD AGE INT 
-- DROP COLUMN NAME 
-- ALTER/MODIFY COLUMN NAME

 --rollback transaction createtables 

 --commit transaction createtables 

 select * from person 

 insert into PERSON
	values(
		2, 'Jane', 'Doe', 'Borno 45', 'Eko','janedoe@gmail.com', 23
	)

select * from person 

-- create new tables 
-- customers, orders, 

create table ORDERS(
				ORDERID INT PRIMARY KEY,
				ORDER_NO INT NOT NULL,
				PERSONID INT FOREIGN KEY REFERENCES PERSON(PERSONID)
				)

INSERT INTO ORDERS
    VALUES(1, 1001,1),
		  (2, 1002, 2)
		  --(3, 1003, 4) ERROR IS RETURNED BECOS 
		  -- PERSONID 4 DOES NOT EXIST IN PERSON TABLE 

SELECT * FROM PERSON
SELECT * FROM ORDERS

-- SQL CHECK CONSTRAINT 
-- USED TO ADD A CHECK ON A COLUMN 
-- IT CAN BE APPLIED ON TABLE CREATION OR 
-- ALTER TABLE 

ALTER TABLE PERSON
ADD CHECK (AGE >= 18)

SELECT * FROM PERSON

INSERT INTO PERSON
	VALUES(3, 'JOY', 'BOLU', 'IKEJA 55', 'IKEJA', 'JOYB@GMAIL.COM', 18)

	SELECT * FROM pERSON

	-- HANDLING UNIQUE IDs
	-- USING SQL AUTO INCREMENT 
	-- USE THE IDENTITY FUNCTION TO DETERMINE A STARTING VALLUE 
	-- AND AN INCREMENT

	CREATE TABLE CUSTOMERS(
		CUSTOMERID INT IDENTITY(100,1) PRIMARY KEY,
		LASTNAME NVARCHAR(255) NOT NULL,
		CITY VARCHAR(50) DEFAULT 'LAGOS',
		PRODUCTID INT 
	)

INSERT INTO CUSTOMERS(LASTNAME, CITY, PRODUCTID)
		VALUES('BELLO', 'AGBOR', 1),
			  ('QUEEN', DEFAULT, 2)

SELECT * FROM CUSTOMERS

--UNIQUE IDENTIFIER 

CREATE TABLE PRODUCTS(
		PRODUCTID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
		PRODUCT_NAME VARCHAR(255) NOT NULL,
		BEST_BEFORE DATE,
		MADE_IN VARCHAR(50) DEFAULT 'NIGERIA',
		CUSTOMERID INT FOREIGN KEY REFERENCES CUSTOMERS(CUSTOMERID)
)

INSERT INTO PRODUCTS
			VALUES(DEFAULT, 'VIT C', '12-31-2021', DEFAULT, 100),
				  (DEFAULT, 'VIT E', '12-31-2022', DEFAULT, 101),
				  (DEFAULT, 'VIT D', '12-31-2023', 'USA', 101)

SELECT * FROM PRODUCTS